spring:
  profiles:
    active: local
#server:
#  servlet:
#    context-path: /epichackathonapi/v1

---

spring:
  profiles: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:epichackathondb;DB_CLOSE_ON_EXIT=FALSE
    username: epic
    password: epic123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
---

spring:
  profiles: stage
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:epichackathondb;DB_CLOSE_ON_EXIT=FALSE
    username: epic
    password: epic123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect